
/* ----------------------------------------------------

   IMPORTANT NOTE

   This file was generated by Claude A.I. by Anthropic.

   ---------------------------------------------------- */

(function () {
  "use strict";

  document.documentElement.classList.add("js"); /* This will add a JavaScript-enabled class for CSS animations and progressive enhancement. */

  /* These are the abbreviated month names used when formatting release dates. */
  var MONTHS = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];

  /* Escapes special HTML characters to safely insert dynamic content into the page. */
  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }

  /* Converts the ISO dates (YYYY-MM-DD) into a readable format for the display. */
  function formatDate(iso) {
    var p = String(iso).split("-");
    if (p.length !== 3) return iso;
    return p[2] + " " + (MONTHS[parseInt(p[1], 10) - 1] || "") + " " + p[0];
  }

  /* This will create a single release row containing metadata, title, tags, links and the animated divider line. */
  function buildRow(opts, index) {
    var row = document.createElement(opts.href ? "a" : "div");

    row.className = "item";

    /* Adds link behaviour when a release URL is available. */
    if (opts.href) {
      row.href = opts.href;

      /* Opens external links in a new tab with security protection. */
      if (/^https?:/.test(opts.href)) {
        row.target = "_blank";
        row.rel = "noopener";
      }
    }

    /* This adds a staggered animation delay for each release entry. */
    row.style.setProperty("--delay", (index * 0.08) + "s");

    /* This will build the HTML structure for the release row. */
    row.innerHTML =
      '<span class="item__meta">' + esc(opts.meta) + "</span>" +
      '<span class="item__title">' + esc(opts.title) +
        (opts.sub ? " <em>" + esc(opts.sub) + "</em>" : "") +
        (opts.latest ? ' <span class="item__latest">Latest release</span>' : "") +
        "</span>" +
      '<span class="item__tag">' + esc(opts.tag) + "</span>" +
      '<span class="item__rule"></span>';

    return row;
  }

  /* This initializes the page builder and populates release lists from the data.js file. */
  function start() {

    /* Generate upcoming release entries from the upcoming data array. */
    var up = document.querySelector("[data-upcoming]");

    if (up && typeof UPCOMING !== "undefined") {
      UPCOMING.forEach(function (item, i) {
        up.appendChild(buildRow({
          meta: formatDate(item.date),
          title: item.title,
          sub: item.feat,
          tag: item.note,
          href: item.url
        }, i));
      });
    }

    /* Generate previous release entries from the latest data array. */
    var prev = document.querySelector("[data-releases]");

    if (prev && typeof LATEST !== "undefined") {

      /* Uses the Spotify artist page as a fallback when no release link exists. */
      var fallback = (typeof SPOTIFY_ARTIST !== "undefined") ? SPOTIFY_ARTIST : "";

      /* Limits displayed releases when data-releases is provided because without a limit, all releases are displayed. */
      var limit = parseInt(prev.getAttribute("data-releases"), 10);
      var shown = isNaN(limit) ? LATEST : LATEST.slice(0, limit);

      /* Create release rows from the selected release list. */
      shown.forEach(function (item, i) {
        prev.appendChild(buildRow({
          meta: item.Year,
          title: item.Title,
          tag: item.Type,
          href: item.url || fallback,

          /* The list is newest first, so the first row is the latest release. */
          latest: i === 0
        }, i));
      });
    }

    /* Start the release row animations after the page has rendered. */
    requestAnimationFrame(function () {
      document.body.classList.add("drawn");
    });
  }

  /* Waits for the document to load before generating the page content. */
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", start);
  } else {
    start();
  }

})();
